import "@/styles/globals.css";

import { type Metadata } from "next";
import { AuthProvider } from "./_components/authProvider";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Papelaria dos Cria",
  description: "Generated by create-t3-app",
  icons: { icon: "/imagens/logo_site.png", },
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <AuthProvider>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        </AuthProvider>
        <Toaster/>
      </body>
    </html>
  );
}
